name: quant-from-zero
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - jupyter
  - jupyterlab
  - pip:
    - yfinance
    - backtrader
    - quantstats
    - ta-lib
    - quarto
