name: Quarto Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python deps (optional)
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy matplotlib scikit-learn jupyter
      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
